chore(CI): bump node version
glayzzle/php-parser pull request #1116
Opened 2023-06-07 06:58 UTC by czosel

Node 14 is EOL. @cseufert strictly speaking this is a breaking change - should we treat it as such?

2023-06-07 23:42 UTC, cseufert commented
We are not yet breaking on node14 are we? Do we need to hard drop support for it, or should we wait until a dependency/feature can no longer support node 14?

2023-06-08 08:44 UTC, czosel commented
Totally, we aren’t. Shall we leave node 14 in CI until it breaks then?

2023-06-09 00:50 UTC, cseufert commented
Yes, I think we leave it, and once it breaks our next release will drop support for it.

2023-06-09 00:51 UTC, cseufert requested changes

2023-06-09 00:51 UTC, cseufert commented on .github/workflows/test.yml
> +        node-version: [16.x, 18.x, 20.x]
```suggestion
        node-version: [14.x, 16.x, 18.x, 20.x]
```

Keep node 14.x support for now

2023-06-12 23:20 UTC, cseufert approved these changes
LGTM

2023-06-13 05:56 UTC, merged