Fix Typed Class Constants parsing
glayzzle/php-parser pull request #1140
Opened 2024-11-25 03:48 UTC by genintho

Fix https://github.com/glayzzle/php-parser/issues/1133

- make sure all variation of class constant are still being supported
- Throw a clear error when the parser detect typed class constants by the PHP version configured does not match

2024-11-25 07:34 UTC, cseufert commented on test/snapshot/__snapshots__/attributes.test.js.snap
> +            },
This does not make sense either, nullable should be a bool value? looks like attrGroups and nullable are switched around somewhere

2024-11-25 07:43 UTC, cseufert requested changes
It looks like the refactor has significantly changed the AST output around attrgroups, as the attrGroups should not be affected, also I would expect nullable to be a boolean type.

2024-11-26 03:10 UTC, genintho commented
@cseufert Yeah there are bugs in the logic.
Can you look at this different PR I made that fix some other bugs I found while working on this https://github.com/glayzzle/php-parser/pull/1141

2024-11-30 01:31 UTC, genintho commented
I figured out the core issue: the AST ClassConstant object `constants` which is an array of AST "Constant" object.

```
ClassConstant {
          "attrGroups": undefined,
          "constants": [
            Constant {
              "kind": "constant",
              "name": Identifier {
                "kind": "identifier",
                "name": "CON_2",
              },
              "value": String {
                "isDoubleQuote": true,
                "kind": "string",
                "raw": ""Hello world!"",
                "unicode": false,
                "value": "Hello world!",
              },
            },
          ],
          "final": false,
          "kind": "classconstant",
          "nullable": [],
          "type": null,
          "visibility": "",
        },
```

The code is reading a list of constant, to support this syntax.

```php
class Foo {
    const PRI1 = 'baz', PRI2 = 'baz2';
}
```

But the implementations made the assumption that all constant have the same type/nullable: type and nullable was added to "ClassConstant", not "Constant". 

That's incorect, because this code is valid:

```
class Foo {
	private const PRI1 = 'baz', string PRI2 = 'baz2', int PRI3 = 5;
}
```

The last commit I pushed, 94d406975c251192c653dc8284c2cd7a31195c6e keep the type on the "ClassConstant" object and create only 1 constant object per ClassConstant. That works, but it is a less accurate representation of the code being parsed. 

Now I am going to fix that by moving the type to the AST "Constant" object.

2024-11-30 07:25 UTC, genintho commented on test/snapshot/__snapshots__/constantstatement.test.js.snap
> +          "type": undefined,
If we do not want those to be part of the AST, we need to completly decouple the ClassConstant object from the Constant object.

2024-11-30 21:37 UTC, genintho commented
@cseufert code is ready for another review

2024-12-01 21:36 UTC, genintho commented
Actually, they are still bug. I will reopen when it is fully ready.

2024-12-01 21:36 UTC, closed without merging